interface = [
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Ticker Bloomberg',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': False,
        'disabled': False,
        'cell': 'C20'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'ISIN',
        'style': 'width: 100%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'B21'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Name',
        'style': 'width: 100%; opacity: 0.8',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C21'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Px Last',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C22'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Currency',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C23'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Cross',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C24'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'App.cross',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C25'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Price Euro',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C26'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Quantity',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': 0.0,
        'filled': False,
        'disabled': False, 
        'cell': 'C29'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Cash-out euro',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C32'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Trade as a % NAV',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C34'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Buy',
        'OBJECT': 'Select',
        'label': 'Broker',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'disabled': False,
        'items': [
            'Not specified',
            'Equita Sim',
            'DBS Vickers',
            'Samsung Securities',
            'GMSA',
            'Tavira Securities',
            'BOFAMLY',
            'IMI',
        ],
        'cell': 'C77'
    }
    ,
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Buy',
        'OBJECT': 'Select',
        'label': 'To work % volume',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'disabled': False,
        'items': [
            '1/3',
            '1/5',
            '1/7'
        ],
        'cell': 'C73'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'ISIN',
        'style': 'width: 100%; opacity: 0.7',
        'v_model': None,
        'filled': False,
        'disabled': False,
        'cell': 'C155'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Px Last',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C158'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Currency',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C159'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Cross',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C160'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'App.cross',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C161'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Quantity',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': 0.0,
        'filled': False,
        'disabled': False,
        'cell': 'C164'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Cash-out euro',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C167'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Trade as a % NAV',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C169'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Buy',
        'OBJECT': 'Select',
        'label': 'Broker',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'disabled': False,
        'items': [
            'Not specified',
            'Equita Sim',
            'DBS Vickers',
            'Samsung Securities',
            'GMSA',
            'Tavira Securities',
            'BOFAMLY',
            'IMI',
        ],
        'cell': 'C196'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'ISIN',
        'style': 'width: 100%; opacity: 0.7',
        'v_model': None,
        'filled': False,
        'disabled': False,
        'cell': 'C90'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Px Last',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C93'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Currency',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C94'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Cross',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
         'cell': 'C95'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'App.cross',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C96'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Mininum Piece',
        'style': 'width: 50%; opacity: 0.8',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C98'

    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Quantity',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': 0.0,
        'filled': False,
        'disabled': False,
        'cell': 'C99'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Market Value Local Currency',
        'style': 'width: 50%; opacity: 0.8',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C101'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Days Acc',
        'style': 'width: 50%; opacity: 0.9',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C102'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Interest Accr.',
        'style': 'width: 50%; opacity: 0.10',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C103'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Accrued',
        'style': 'width: 50%; opacity: 0.11',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C104'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'Select',
        'label': 'Broker',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'disabled': False,
        'items': [
            'Not specified',
            'Equita Sim',
            'DBS Vickers',
            'Samsung Securities',
            'GMSA',
            'Tavira Securities',
            'BOFAMLY',
            'IMI',
        ],
        'cell': 'C141'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Cash-out euro',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C105'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Buy',
        'OBJECT': 'TextField',
        'label': 'Trade as a % NAV',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C107'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Ticker Bloomberg',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': False,
        'disabled': False,
        'cell': 'C19'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'ISIN',
        'style': 'width: 100%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'B20'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Name',
        'style': 'width: 100%; opacity: 0.8',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C20'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Px Last',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C27'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Currency',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C28'  
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Cross',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C29'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'App.cross',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C30'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Price Euro',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C31'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Quantity',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': 0.0,
        'filled': False,
        'disabled': False,
        'cell': 'C24'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Total existing position',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C22'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': '% of the position to be sold',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C23'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Cash-in euro',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C34'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Trade as a % NAV',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C35'
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'Select',
        'label': 'Broker',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'disabled': False,
        'items': [
            'Not specified',
            'Equita Sim',
            'DBS Vickers',
            'Samsung Securities',
            'GMSA',
            'Tavira Securities',
            'BOFAMLY',
            'IMI',
        ],
        'cell': 'C55'        
    },
    {
        'INSTRUMENT': 'Equity',
        'TYPE': 'Sell',
        'OBJECT': 'Select',
        'label': 'To work % volume',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'disabled': False,
        'items': [
            '1/3',
            '1/5',
            '1/7'
        ],
        'cell': 'C52'
    },
    {

        'INSTRUMENT': 'Fund',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'ISIN',
        'style': 'width: 100%; opacity: 0.7',
        'v_model': None,
        'filled': False,
        'disabled': False,
        'cell': 'C116'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Name',
        'style': 'width: 100%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C117'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Px Last',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C125'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Currency',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C126'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Cross',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C127'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'App.cross',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C128'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Total existing position',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C119'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': '% of the position to be sold',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': False,
        'disabled': False,
        'cell': 'C121'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Quantity',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C123'
        
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Cash-in euro',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C129'
    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Trade as a % NAV',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C130'

    },
    {
        'INSTRUMENT': 'Fund',
        'TYPE': 'Sell',
        'OBJECT': 'Select',
        'label': 'Broker',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'disabled': False,
        'items': [
            'Not specified',
            'Equita Sim',
            'DBS Vickers',
            'Samsung Securities',
            'GMSA',
            'Tavira Securities',
            'BOFAMLY',
            'IMI',
        ],
        'cell': 'C146'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'ISIN',
        'style': 'width: 100%; opacity: 0.7',
        'v_model': None,
        'filled': False,
        'disabled': False,
        'cell': 'C68'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Px Last',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C80'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Currency',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C81'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Cross',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C82'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'App.cross',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C83'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Total existing position',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C71'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': '% of the position to be sold',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': False,
        'disabled': False,
        'cell': 'C73'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Mininum Piece',
        'style': 'width: 50%; opacity: 0.8',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C77'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Quantity',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C75'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Days Acc',
        'style': 'width: 50%; opacity: 0.9',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C84'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Interest Accr.',
        'style': 'width: 50%; opacity: 0.10',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C85'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Accrued',
        'style': 'width: 50%; opacity: 0.11',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C86'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'Select',
        'label': 'Broker',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'disabled': False,
        'items': [
            'Not specified',
            'Equita Sim',
            'DBS Vickers',
            'Samsung Securities',
            'GMSA',
            'Tavira Securities',
            'BOFAMLY',
            'IMI',
        ],
        'cell': 'C104'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Cash-in euro',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C87'
    },
    {
        'INSTRUMENT': 'Bond',
        'TYPE': 'Sell',
        'OBJECT': 'TextField',
        'label': 'Trade as a % NAV',
        'style': 'width: 50%; opacity: 0.7',
        'v_model': None,
        'filled': True,
        'disabled': True,
        'cell': 'C88'
    }
]


